import { chromium } from 'playwright'
import { mkdir, readFile, writeFile } from 'node:fs/promises'

function makeToneWav(seconds = 0.18, frequency = 110) {
  const rate = 44_100
  const frames = Math.floor(rate * seconds)
  const output = Buffer.alloc(44 + frames * 2)
  output.write('RIFF', 0); output.writeUInt32LE(output.length - 8, 4); output.write('WAVE', 8)
  output.write('fmt ', 12); output.writeUInt32LE(16, 16); output.writeUInt16LE(1, 20); output.writeUInt16LE(1, 22)
  output.writeUInt32LE(rate, 24); output.writeUInt32LE(rate * 2, 28); output.writeUInt16LE(2, 32); output.writeUInt16LE(16, 34)
  output.write('data', 36); output.writeUInt32LE(frames * 2, 40)
  for (let frame = 0; frame < frames; frame += 1) {
    const envelope = Math.max(0, 1 - frame / frames)
    output.writeInt16LE(Math.round(Math.sin(frame / rate * frequency * Math.PI * 2) * envelope * 14_000), 44 + frame * 2)
  }
  return output
}

const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, acceptDownloads: true })
const errors = []
page.on('pageerror', (error) => errors.push(error.message))
await page.goto('http://127.0.0.1:5173', { waitUntil: 'domcontentloaded' })
await page.waitForSelector('.workstation-shell')
await page.getByRole('button', { name: 'OVERVIEW', exact: true }).click()
if (await page.locator('.song-bar').count() !== 48) throw new Error('Authored arrangement is not 48 bars')

const rangeAudit = await page.evaluate(async () => {
  const controls = [...document.querySelectorAll('input[type="range"]')]
  const unnamed = controls.filter((input) => !input.getAttribute('aria-label') && !input.closest('label')?.textContent?.trim())
  if (unnamed.length) throw new Error(`${unnamed.length} range controls have no accessible name`)
  let changed = 0
  for (const input of controls.filter((control) => !control.disabled)) {
    const original = input.value
    const min = Number(input.min || 0)
    const max = Number(input.max || 100)
    const midpoint = String(min + (max - min) * (original === String(min + (max - min) / 2) ? 0.37 : 0.5))
    const setValue = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')?.set
    setValue?.call(input, midpoint)
    input.dispatchEvent(new Event('input', { bubbles: true }))
    input.dispatchEvent(new Event('change', { bubbles: true }))
    await new Promise((resolve) => requestAnimationFrame(() => resolve()))
    if (input.value === original) throw new Error(`Range control did not update: ${input.getAttribute('aria-label') || input.closest('label')?.textContent}`)
    changed += 1
    setValue?.call(input, original)
    input.dispatchEvent(new Event('input', { bubbles: true }))
    input.dispatchEvent(new Event('change', { bubbles: true }))
    await new Promise((resolve) => requestAnimationFrame(() => resolve()))
  }
  return { total: controls.length, changed }
})
console.log(`CONTROL_AUDIT ${rangeAudit.changed}/${rangeAudit.total} active range controls changed and restored`)

const whiteKeys = page.locator('.unit-1 .white-key')
const blackKeys = page.locator('.unit-1 .black-key')
if (await whiteKeys.count() !== 8 || await blackKeys.count() !== 5) throw new Error('Piano keyboard geometry is incomplete')
const firstWhite = await whiteKeys.first().boundingBox()
const firstBlack = await blackKeys.first().boundingBox()
if (!firstWhite || !firstBlack || firstBlack.x <= firstWhite.x || firstBlack.y !== firstWhite.y) throw new Error('Piano black keys are misaligned')
await whiteKeys.first().focus()
await whiteKeys.first().press('Enter')
const piano = page.locator('.unit-1 .piano-keyboard')
const octaveBefore = await piano.locator('.piano-octave-readout').textContent()
await page.locator('.unit-1').getByRole('button', { name: 'Piano octave up' }).click()
if (await piano.locator('.piano-octave-readout').textContent() === octaveBefore) throw new Error('Piano octave button did not shift the key range')

const bassClearStep = page.locator('.unit-1 .bass-steps button').first()
await bassClearStep.click({ button: 'right' })
if (await bassClearStep.getAttribute('aria-pressed') !== 'false' || await bassClearStep.evaluate((button) => button.classList.contains('accent') || button.classList.contains('slide'))) throw new Error('Right-click did not fully clear the bass step')
await page.locator('.unit-1').getByRole('button', { name: 'WIPE ALL', exact: true }).click()
if (await page.locator('.unit-1 .bass-steps button.on').count() || await page.locator('.unit-1 .bass-steps button.accent,.unit-1 .bass-steps button.slide').count()) throw new Error('303 Wipe 16 left note modifiers behind')
const bassCutoff = page.locator('.unit-1').getByRole('slider', { name: 'CUTOFF', exact: true })
await bassCutoff.fill('99')
await page.locator('.unit-1').getByRole('button', { name: 'DEFAULT', exact: true }).click()
if (await bassCutoff.inputValue() === '99') throw new Error('303 Default did not restore sound controls')

const computerKeys = page.locator('.computer-keyboard')
if (!await computerKeys.count()) throw new Error('Computer keyboard performance control is missing')
await page.keyboard.down('z')
if (!await computerKeys.locator('.key-map-row span.pressed').count()) throw new Error('Tonal computer key did not engage')
await page.keyboard.up('z')
await computerKeys.getByRole('button', { name: '808', exact: true }).click()
await page.keyboard.down('q')
if (!await computerKeys.locator('.key-map-row span.pressed').count()) throw new Error('Drum computer key did not engage')
await page.keyboard.up('q')

const waveDesigner = page.locator('#wave-designer')
if (!await waveDesigner.count()) throw new Error('Wave Designer is missing')
await waveDesigner.getByRole('button', { name: 'SQUARE', exact: true }).click()
if (await waveDesigner.getByRole('button', { name: 'SQUARE', exact: true }).getAttribute('aria-pressed') !== 'true') throw new Error('Wave Designer oscillator did not change')
await waveDesigner.getByRole('button', { name: 'LOAD INTO 303·1', exact: true }).click()
if (await page.locator('.unit-1').getByRole('button', { name: 'WAVE', exact: true }).getAttribute('aria-pressed') !== 'true') throw new Error('Wave Designer patch did not transfer to 303·1')
if (!await page.locator('.unit-1 .designer-source-readout').getByText('SQUARE', { exact: true }).count()) throw new Error('303·1 did not receive the designed waveform')
await waveDesigner.locator('.designer-steps button').first().click()
await waveDesigner.locator('.piano-keyboard .white-key').first().click()
await page.getByRole('button', { name: 'Mute WAVE' }).click()
await page.getByRole('button', { name: 'Mute WAVE' }).click()

await page.locator('.global-actions').getByRole('button', { name: 'LIVE', exact: true }).click()
if (!await page.locator('.workstation-shell.performance-view').count()) throw new Error('Live view did not engage')
await page.locator('.global-actions').getByRole('button', { name: 'MEDIA', exact: true }).click()
await page.waitForFunction(() => (document.querySelector('#media-bay')?.getBoundingClientRect().y ?? 9999) < 300)
if (await page.locator('.workstation-shell.performance-view').count()) throw new Error('Media jump did not leave compact Live view')
const mediaBox = await page.locator('#media-bay').boundingBox()
if (!mediaBox || mediaBox.y > 300) throw new Error('Media jump did not reveal the decks')
await page.waitForFunction(() => [...document.querySelectorAll('.media-deck')].every((deck) => !deck.textContent?.includes('NO MEDIA')))
if (await page.locator('.sample-pads button.loaded').count() !== 8) throw new Error('Starter sampler bank did not decode all eight bundled sounds')

const initialNotes = await page.locator('.unit-1 .bass-steps').innerText()
await page.locator('.unit-1 .pattern-row.banks button').nth(1).click()
const changedNotes = await page.locator('.unit-1 .bass-steps').innerText()
if (initialNotes === changedNotes) throw new Error('Bass pattern bank did not change musical data')

await page.locator('.drum-808 .drum-voices button').nth(1).click()
await page.locator('.drum-808 .drum-step-bank button').nth(2).click()
await page.locator('.drum-808').getByRole('button', { name: 'WIPE ALL', exact: true }).click()
if (await page.locator('.drum-808 .drum-step-bank button.on').count()) throw new Error('Drum Wipe 16 did not clear the current machine pattern')
await page.getByRole('button', { name: 'Mute 808' }).click()
if (await page.getByRole('button', { name: 'Mute 808' }).getAttribute('aria-pressed') !== 'true') throw new Error('Drum mixer mute did not engage')
await page.getByRole('button', { name: 'Mute 808' }).click()

if (await page.locator('.fx-pads button').count() !== 12) throw new Error('Performance Lab does not expose twelve FX sounds')
for (const pad of await page.locator('.fx-pads button').all()) await pad.click()
await page.locator('.repeat-bank button').nth(2).click()
if (!await page.locator('.repeat-bank button.active').count()) throw new Error('Beat repeat did not engage')
await page.locator('.repeat-bank button').nth(2).click()

const crossfader = page.getByRole('slider', { name: 'Performance crossfader' })
await crossfader.fill('-65')
if (await crossfader.inputValue() !== '-65') throw new Error('Crossfader did not update')
await crossfader.fill('100')
await page.waitForFunction(() => document.querySelector('.media-deck')?.textContent?.includes('CROSSFADER CUT'))
await page.locator('.media-deck').first().getByRole('button', { name: 'RESTORE SOUND', exact: true }).click()
if (await crossfader.inputValue() !== '0') throw new Error('Deck sound recovery did not center the crossfader')
if (!await page.locator('.media-deck').first().getByText('ROUTING READY', { exact: false }).count()) throw new Error('Deck A did not return to an audible routing state')

const smoothSwitch = page.getByRole('button', { name: 'SOFTEN ON', exact: true })
await smoothSwitch.click()
if (await page.getByRole('button', { name: 'SOFTEN OFF', exact: true }).getAttribute('aria-pressed') !== 'false') throw new Error('Smooth output switch did not disengage')
await page.getByRole('button', { name: 'SOFTEN OFF', exact: true }).click()
const echoMix = page.getByRole('slider', { name: 'Global echo mix' })
const reverbMix = page.getByRole('slider', { name: 'Global reverb mix' })
await echoMix.fill('0')
await reverbMix.fill('0')
await page.getByRole('button', { name: 'ALL ECHO FX ON', exact: true }).click()
if (await page.getByRole('button', { name: 'ALL ECHO FX OFF', exact: true }).getAttribute('aria-pressed') !== 'false') throw new Error('Shared FX bypass did not engage')
if (!await page.locator('.repeat-bank').getByText(/BYPASSED BY ALL ECHO FX OFF/).count()) throw new Error('Beat Repeat bypass status is not visible')
await page.getByRole('button', { name: 'ALL ECHO FX OFF', exact: true }).click()

await page.getByRole('button', { name: 'Play', exact: true }).click()
await page.waitForTimeout(650)
if (await page.locator('.playing').count() === 0) throw new Error('Sequencer playhead did not advance')
if (await page.locator('.meter i.lit').count() === 0) throw new Error('Audio engine produced no metered output')
await page.getByRole('button', { name: 'Stop', exact: true }).click()

await page.getByRole('button', { name: 'SONG', exact: true }).click()
await page.waitForSelector('.song-strip')
await page.getByRole('button', { name: /CAPTURE CURRENT/ }).click()
await page.getByRole('button', { name: /INSERT AFTER/ }).click()
if (await page.locator('.song-bar').count() !== 49) throw new Error('Arrangement insert failed')
if (!await page.locator('.section-launchers button').nth(1).textContent().then((text) => text?.includes('10–17'))) throw new Error('Scene markers did not move with inserted bar')
await page.getByRole('button', { name: /REMOVE BAR/ }).click()
if (await page.locator('.song-bar').count() !== 48) throw new Error('Arrangement remove failed')
await page.locator('.song-bar').nth(2).click()
await page.getByRole('button', { name: 'MARK SCENE HERE' }).click()
if (await page.locator('.section-launchers button').count() !== 7) throw new Error('Scene marker was not added')
await page.getByRole('textbox', { name: 'Active scene name' }).fill('VERSE')
if (!await page.locator('.scene-bank').getByRole('button', { name: /VERSE/ }).count()) throw new Error('Scene rename did not reach Performance Lab')
await page.getByRole('button', { name: 'REMOVE MARKER' }).click()
if (await page.locator('.section-launchers button').count() !== 6) throw new Error('Scene marker was not removed')
await page.locator('.scene-bank button').nth(1).click()
if ((await page.locator('.digital-readout').first().locator('strong').textContent())?.trim() !== '009') throw new Error('Scene launch did not jump to its first bar')
await page.getByRole('button', { name: 'Play', exact: true }).click()
await page.waitForTimeout(180)
if ((await page.locator('.digital-readout').first().locator('strong').textContent())?.trim() !== '009') throw new Error('Transport reset a selected scene on play')
await page.getByRole('button', { name: 'Stop', exact: true }).click()

await mkdir('artifacts', { recursive: true })
const loadMedia = process.env.SKIP_MEDIA !== '1'
if (loadMedia) {
  await writeFile('artifacts/test-tone.wav', makeToneWav())
  await page.locator('.media-deck').first().locator('input[type=file]').setInputFiles('artifacts/test-tone.wav')
  await page.waitForFunction(() => document.querySelector('.media-deck')?.textContent?.includes('1CH'))
  const firstDeck = page.locator('.media-deck').first()
  const seek = page.getByRole('slider', { name: 'Deck A position' })
  await seek.fill('0.05')
  if (Math.abs(Number(await seek.inputValue()) - 0.05) > 0.02) throw new Error('Deck seek did not update')
  const loop = firstDeck.getByRole('button', { name: 'LOOP' })
  const loopBefore = await loop.getAttribute('aria-pressed')
  await loop.click()
  if (await loop.getAttribute('aria-pressed') === loopBefore) throw new Error('Deck loop did not toggle')
  if (await loop.getAttribute('aria-pressed') !== 'true') await loop.click()
  await page.locator('.media-deck').first().getByRole('button', { name: /PLAY/ }).click()
  await page.waitForSelector('.media-deck.is-playing')
  await page.getByRole('slider', { name: 'Deck A pitch' }).fill('5')
  await page.getByRole('slider', { name: 'Deck A playback rate' }).fill('1.2')
  await page.getByRole('slider', { name: 'Deck A jog wheel' }).press('ArrowRight')
  await page.waitForTimeout(220)
  if (!await firstDeck.evaluate((deck) => deck.classList.contains('is-playing'))) throw new Error('Live deck controls interrupted playback')
  if (await page.locator('.meter i.lit').count() === 0) throw new Error('Deck A is playing but produces no master-bus signal')
  await page.locator('.media-deck').first().getByRole('button', { name: /PAUSE/ }).click()

  await page.locator('.sampler-bay input[type=file]').setInputFiles('artifacts/test-tone.wav')
  await page.waitForSelector('.sample-pads button.loaded')
  if (await page.locator('.sample-bank-toolbar button').count() !== 7) throw new Error('Sampler bank and 16-level controls are incomplete')
  if (await page.locator('.sample-waveform svg line').count() < 100) throw new Error('Sample waveform did not render')
  await page.locator('.chop-actions').getByRole('button', { name: 'AUTO 4' }).click()
  if (await page.locator('.sample-pads button.loaded').count() < 4) throw new Error('Transient chopping did not map four pads')
  await page.locator('.sample-file-actions').getByRole('button', { name: 'DUP' }).click()
  if (await page.locator('.sample-pads button.loaded').count() < 5) throw new Error('Sample duplication failed')
  await page.locator('.sample-modes').getByRole('button', { name: 'NORMALIZE' }).click()
  await page.locator('.sample-modes').getByRole('button', { name: 'WARP' }).click()
  await page.getByRole('slider', { name: 'Sample step velocity' }).fill('73')
  await page.getByRole('slider', { name: 'Sample step nudge' }).fill('-12')
  await page.getByRole('slider', { name: 'Sample step probability' }).fill('84')
  await page.getByRole('slider', { name: 'Sample step ratchet' }).fill('3')
  await page.locator('.sample-bank-toolbar').getByRole('button', { name: 'B', exact: true }).click()
  if (await page.locator('.sample-pads button.loaded').count()) throw new Error('Sampler bank B did not reveal its own pads')
  await page.locator('.sample-bank-toolbar').getByRole('button', { name: 'A', exact: true }).click()
  await page.locator('.sample-bank-toolbar').getByRole('button', { name: '16 PITCH', exact: true }).click()
  await computerKeys.getByRole('button', { name: 'SAMPLE', exact: true }).click()
  await page.keyboard.down('z')
  if (!await computerKeys.locator('.key-map-row span.pressed').count()) throw new Error('Sampler 16-level keyboard mode did not engage')
  await page.keyboard.up('z')
  await page.locator('.resample-strip').getByRole('combobox', { name: 'Resample source' }).selectOption('deck0')
  await page.locator('.resample-strip').getByRole('button', { name: /PRINT 1 BAR/ }).click()
  await page.waitForFunction(() => document.querySelector('.sample-identity strong')?.textContent?.includes('PRINT DECK A'))
  await page.locator('.sample-pads button').first().dispatchEvent('pointerdown')
  await page.locator('.sample-pads button').first().dispatchEvent('pointerup')
  await page.locator('.sample-pads button').first().press('Enter')
  await page.locator('.sample-sequencer button').first().click()
  await page.getByRole('slider', { name: 'Sample step velocity' }).fill('64')
  await page.getByRole('slider', { name: 'Sample step ratchet' }).fill('4')
  await page.locator('.sample-sequencer button').first().click({ button: 'right' })
  if (await page.locator('.sample-sequencer button').first().getAttribute('aria-pressed') !== 'false') throw new Error('Sampler right-click did not clear its trigger')
  if (await page.getByRole('slider', { name: 'Sample step velocity' }).inputValue() !== '100' || await page.getByRole('slider', { name: 'Sample step ratchet' }).inputValue() !== '1') throw new Error('Sampler right-click did not reset per-step modulation')
}

await page.getByRole('button', { name: 'Help' }).click()
if (!await page.locator('.help-grid').getByText('USE SCENES LIVE', { exact: false }).count()) throw new Error('Workstation explainer is incomplete')
await page.getByRole('button', { name: 'Close help' }).click()

if (await page.locator('.source-mixer .channel-strip').count() !== 8) throw new Error('Expanded mixer does not expose eight channels')

await page.getByRole('button', { name: 'Projects', exact: true }).click()
await page.getByRole('button', { name: /SAVE CURRENT PROJECT/ }).click()
if (!await page.evaluate(() => Boolean(localStorage.getItem('rebirth338:projects')))) throw new Error('Project was not persisted')
await page.locator('.projects-popover header > button').click()

const downloadPromise = page.waitForEvent('download', { timeout: 120_000 })
if (process.env.SHORT_EXPORT === '1') await page.getByRole('button', { name: 'PATTERN', exact: true }).click()
await page.getByRole('button', { name: /EXPORT .* WAV/ }).click()
const download = await downloadPromise
await download.saveAs('artifacts/reborn-smoke.wav')
const wav = await readFile('artifacts/reborn-smoke.wav')
if (wav.subarray(0, 4).toString() !== 'RIFF' || wav.length < 100_000) throw new Error('WAV export is invalid or empty')

if (errors.length) throw new Error(`Page errors: ${errors.join('; ')}`)
console.log(JSON.stringify({ buttons: await page.locator('button').count(), wavBytes: wav.length, bars: 48, deckLoaded: loadMedia, samplerLoaded: loadMedia, piano: '8 white / 5 black', patternChanged: true, songMode: true, pageErrors: 0 }))
await browser.close()
